### ISSUE TITLE
empty link on top of page nav

### ISSUE THREAD

**Issue by evanwill** [uidaholib/main-web-redesign_draft#429]
why?

**Comment by evanwill** [comment]
i know why. Each section is a list, the first list item is `parent`, it doesn't have any of the attributes the pagenav is looping over, thus causes an empty.

**Comment by evanwill** [comment]
i want to change the "pagesnav.yml" structure to make it more useable eventually. Something like:

```
About: 
 section-name: About
 stub: /about/
 pages: 
  - subsection: About Home
    link: /about/
  - subsection: Against Racism
    link: /about/commitment-to-act-against-racism.html
  - subsection: Contact
    link: /about/contact.html
```
