### ISSUE TITLE
restructure pagesnav.yml

### ISSUE THREAD

**Issue by evanwill** [uidaholib/main-web-redesign_draft#492]
restructure to make more usable and sensible. something like:

```
sections: 
 - section-name: About
   stub: /about/
   description: "stuff about the library"
   pages: 
    - subsection: About Home
      link: /about/
    - subsection: Against Racism
      link: /about/commitment-to-act-against-racism.html
    - subsection: Contact
      link: /about/contact.html
```
